### ISSUE TITLE
Scaffolding not working in Rails 5.1.0-beta1

### ISSUE THREAD

**Issue by michaelimstepf** [slim-template/slim-rails#139] opened 2017-03-03 19:59 UTC
Installed Rails 5.1.0-beta1 last night and got the following error with `slim-rails (3.1.2)`. Is this a Rails issue or a slim-rails issue?

```
$ rails g scaffold_controller Workspace
Running via Spring preloader in process 11229
Expected string default value for '--test-framework'; got false (boolean)
      create  app/controllers/workspaces_controller.rb
      invoke  slim
      create    app/views/workspaces
/Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.beta1/lib/rails/generators/erb.rb:20:in `filename_with_extensions': private method `format' called for #<Slim::Generators::ScaffoldGenerator:0x007ff5c5b12f70> (NoMethodError)
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/slim-rails-3.1.2/lib/generators/slim/scaffold/scaffold_generator.rb:10:in `block in copy_view_files'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/slim-rails-3.1.2/lib/generators/slim/scaffold/scaffold_generator.rb:9:in `each'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/slim-rails-3.1.2/lib/generators/slim/scaffold/scaffold_generator.rb:9:in `copy_view_files'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.beta1/lib/rails/generators/rails/scaffold_controller/scaffold_controller_generator.rb:24:in `block in <class:ScaffoldControllerGenerator>'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/group.rb:274:in `instance_exec'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/group.rb:274:in `block in _invoke_for_class_method'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/shell.rb:68:in `with_padding'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/group.rb:266:in `_invoke_for_class_method'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/group.rb:133:in `_invoke_from_option_template_engine'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.beta1/lib/rails/generators.rb:269:in `invoke'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.beta1/lib/rails/commands/generate/generate_command.rb:19:in `perform'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.beta1/lib/rails/command/base.rb:63:in `perform'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.beta1/lib/rails/command.rb:44:in `invoke'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.beta1/lib/rails/commands.rb:16:in `<top (required)>'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:292:in `require'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:292:in `require'
	from /Users/migu/Dev/blocklytics/bin/rails:9:in `<top (required)>'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:286:in `load'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:286:in `block in load'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies.rb:286:in `load'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/migu/.rbenv/versions/2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by januszm** [comment] 2017-03-03 21:14
@michaelimstepf could you put a debugger (`binding.pry` or `byebug`) just after line 20 and see what is `self` ?
in
`/Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.beta1/lib/rails/generators/erb.rb:20`

```ruby
        def filename_with_extensions(name, format = self.format)
          binding.pry
          [name, format, handler].compact.join(".")
        end
```

and type `self` or `self.class`

**Comment by michaelimstepf** [comment] 2017-03-03 21:23
Sure thing. I had to change the arguments because `self` doesn't have a method `format`. Here is the output:

```
rails g scaffold_controller test
Running via Spring preloader in process 18595
Expected string default value for '--test-framework'; got false (boolean)
   identical  app/controllers/tests_controller.rb
      invoke  slim
       exist    app/views/tests

[17, 26] in /Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.beta1/lib/rails/generators/erb.rb
   17:           :erb
   18:         end
   19: 
   20:         def filename_with_extensions(name, format = self)
   21:          byebug 
=> 22:          [name, format, handler].compact.join(".")
   23:         end
   24:     end
   25:   end
   26: end
(byebug) self
#<Slim::Generators::ScaffoldGenerator:0x007fe916b82688 @inside_template=nil, @behavior=:invoke, @_invocations={Rails::Generators::ScaffoldControllerGenerator=>["check_class_collision", "create_controller_files", "_invoke_from_option_template_engine"], Slim::Generators::ScaffoldGenerator=>["create_root_folder", "copy_view_files"]}, @_initializer=[["test"], [], {:behavior=>:invoke, :destination_root=>"/Users/migu/Dev/blocklytics", :shell=>#<Thor::Shell::Color:0x007fe91575e990 @base=#<Rails::Generators::ScaffoldControllerGenerator:0x007fe91575e6e8 @inside_template=false, @behavior=:invoke, @_invocations={Rails::Generators::ScaffoldControllerGenerator=>["check_class_collision", "create_controller_files", "_invoke_from_option_template_engine"], Slim::Generators::ScaffoldGenerator=>["create_root_folder", "copy_view_files"]}, @_initializer=[["test"], [], {:behavior=>:invoke, :destination_root=>#<Pathname:/Users/migu/Dev/blocklytics>, :shell=>#<Thor::Shell::Color:0x007fe91575e990 ...>}], @options={"skip_namespace"=>false, "force_plural"=>false, "helper"=>true, "orm"=>:active_record, "api"=>false, "template_engine"=>:slim, "test_framework"=>false, "jbuilder"=>true}, @attributes=[], @name="test", @args=[], @shell=#<Thor::Shell::Color:0x007fe91575e990 ...>, @destination_stack=["/Users/migu/Dev/blocklytics"], @in_group=nil, @after_bundle_callbacks=[], @class_path=[], @file_name="test", @controller_name="tests", @controller_class_path=[], @controller_file_name="tests", @source_paths=["/Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jbuilder-2.6.3/lib/generators/rails/templates", "/Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.beta1/lib/rails/generators/rails/scaffold_controller/templates"], @output_buffer="class TestsController < ApplicationController\n  before_action :set_test, only: [:show, :edit, :update, :destroy]\n\n  # GET /tests\n  # GET /tests.json\n  def index\n    @tests = Test.all\n  end\n\n  # GET /tests/1\n  # GET /tests/1.json\n  def show\n  end\n\n  # GET /tests/new\n  def new\n    @test = Test.new\n  end\n\n  # GET /tests/1/edit\n  def edit\n  end\n\n  # POST /tests\n  # POST /tests.json\n  def create\n    @test = Test.new(test_params)\n\n    respond_to do |format|\n      if @test.save\n        format.html { redirect_to @test, notice: 'Test was successfully created.' }\n        format.json { render :show, status: :created, location: @test }\n      else\n        format.html { render :new }\n        format.json { render json: @test.errors, status: :unprocessable_entity }\n      end\n    end\n  end\n\n  # PATCH/PUT /tests/1\n  # PATCH/PUT /tests/1.json\n  def update\n    respond_to do |format|\n      if @test.update(test_params)\n        format.html { redirect_to @test, notice: 'Test was successfully updated.' }\n        format.json { render :show, status: :ok, location: @test }\n      else\n        format.html { render :edit }\n        format.json { render json: @test.errors, status: :unprocessable_entity }\n      end\n    end\n  end\n\n  # DELETE /tests/1\n  # DELETE /tests/1.json\n  def destroy\n    @test.destroy\n    respond_to do |format|\n      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }\n      format.json { head :no_content }\n    end\n  end\n\n  private\n    # Use callbacks to share common setup or constraints between actions.\n    def set_test\n      @test = Test.find(params[:id])\n    end\n\n    # Never trust parameters from the scary internet, only allow the white list through.\n    def test_params\n      params.fetch(:test, {})\n    end\nend\n", @plural_name="tests", @table_name="tests", @singular_table_name="test", @plural_file_name="tests", @route_url="/tests", @plural_table_name="tests", @orm_class=Rails::Generators::ActiveModel, @orm_instance=#<Rails::Generators::ActiveModel:0x007fe91679a728 @name="test">, @human_name="Test", @attributes_names=[]>, @mute=false, @padding=1, @always_force=false>, :invocations=>{Rails::Generators::ScaffoldControllerGenerator=>["check_class_collision", "create_controller_files", "_invoke_from_option_template_engine"], Slim::Generators::ScaffoldGenerator=>["create_root_folder", "copy_view_files"]}}], @options={"skip_namespace"=>false, "force_plural"=>false}, @attributes=[], @name="test", @args=[], @shell=#<Thor::Shell::Color:0x007fe91575e990 @base=#<Rails::Generators::ScaffoldControllerGenerator:0x007fe91575e6e8 @inside_template=false, @behavior=:invoke, @_invocations={Rails::Generators::ScaffoldControllerGenerator=>["check_class_collision", "create_controller_files", "_invoke_from_option_template_engine"], Slim::Generators::ScaffoldGenerator=>["create_root_folder", "copy_view_files"]}, @_initializer=[["test"], [], {:behavior=>:invoke, :destination_root=>#<Pathname:/Users/migu/Dev/blocklytics>, :shell=>#<Thor::Shell::Color:0x007fe91575e990 ...>}], @options={"skip_namespace"=>false, "force_plural"=>false, "helper"=>true, "orm"=>:active_record, "api"=>false, "template_engine"=>:slim, "test_framework"=>false, "jbuilder"=>true}, @attributes=[], @name="test", @args=[], @shell=#<Thor::Shell::Color:0x007fe91575e990 ...>, @destination_stack=["/Users/migu/Dev/blocklytics"], @in_group=nil, @after_bundle_callbacks=[], @class_path=[], @file_name="test", @controller_name="tests", @controller_class_path=[], @controller_file_name="tests", @source_paths=["/Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jbuilder-2.6.3/lib/generators/rails/templates", "/Users/migu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0.beta1/lib/rails/generators/rails/scaffold_controller/templates"], @output_buffer="class TestsController < ApplicationController\n  before_action :set_test, only: [:show, :edit, :update, :destroy]\n\n  # GET /tests\n  # GET /tests.json\n  def index\n    @tests = Test.all\n  end\n\n  # GET /tests/1\n  # GET /tests/1.json\n  def show\n  end\n\n  # GET /tests/new\n  def new\n    @test = Test.new\n  end\n\n  # GET /tests/1/edit\n  def edit\n  end\n\n  # POST /tests\n  # POST /tests.json\n  def create\n    @test = Test.new(test_params)\n\n    respond_to do |format|\n      if @test.save\n        format.html { redirect_to @test, notice: 'Test was successfully created.' }\n        format.json { render :show, status: :created, location: @test }\n      else\n        format.html { render :new }\n        format.json { render json: @test.errors, status: :unprocessable_entity }\n      end\n    end\n  end\n\n  # PATCH/PUT /tests/1\n  # PATCH/PUT /tests/1.json\n  def update\n    respond_to do |format|\n      if @test.update(test_params)\n        format.html { redirect_to @test, notice: 'Test was successfully updated.' }\n        format.json { render :show, status: :ok, location: @test }\n      else\n        format.html { render :edit }\n        format.json { render json: @test.errors, status: :unprocessable_entity }\n      end\n    end\n  end\n\n  # DELETE /tests/1\n  # DELETE /tests/1.json\n  def destroy\n    @test.destroy\n    respond_to do |format|\n      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }\n      format.json { head :no_content }\n    end\n  end\n\n  private\n    # Use callbacks to share common setup or constraints between actions.\n    def set_test\n      @test = Test.find(params[:id])\n    end\n\n    # Never trust parameters from the scary internet, only allow the white list through.\n    def test_params\n      params.fetch(:test, {})\n    end\nend\n", @plural_name="tests", @table_name="tests", @singular_table_name="test", @plural_file_name="tests", @route_url="/tests", @plural_table_name="tests", @orm_class=Rails::Generators::ActiveModel, @orm_instance=#<Rails::Generators::ActiveModel:0x007fe91679a728 @name="test">, @human_name="Test", @attributes_names=[]>, @mute=false, @padding=1, @always_force=false>, @destination_stack=["/Users/migu/Dev/blocklytics"], @in_group=nil, @after_bundle_callbacks=[], @class_path=[], @file_name="test", @controller_name="tests", @controller_class_path=[], @controller_file_name="tests", @parent_options={"skip_namespace"=>false, "force_plural"=>false, "helper"=>true, "orm"=>:active_record, "api"=>false, "template_engine"=>:slim, "test_framework"=>false, "jbuilder"=>true}, @controller_file_path="tests">
(byebug) self.class
Slim::Generators::ScaffoldGenerator
(byebug) 
```

**Comment by michaelimstepf** [comment] 2017-03-03 21:29
For anyone experiencing the same issue and want a temporary hack to fix it, change line 20 mentioned above to `def filename_with_extensions(name, format = self.send(:format)) `

**Comment by januszm** [comment] 2017-03-03 21:30
At first glimpse it looks like we need to update Generator for Rails 5.1 since it inherits from `Erb::Generators::ScaffoldGenerator`,  `format` method there got private here:

```ruby
commit d1daf4c31301f5f5917b877fd63a817f5f4608ed
Author: Akira Matsuda <ronnie@dio.jp>
Date:   Fri Dec 23 19:20:01 2016 +0900

    Privatize unneededly protected methods in Railties

diff --git a/railties/lib/rails/generators/erb.rb b/railties/lib/rails/generators/erb.rb
index d015020..d5e326d 100644
--- a/railties/lib/rails/generators/erb.rb
+++ b/railties/lib/rails/generators/erb.rb
@@ -3,7 +3,7 @@
 module Erb # :nodoc:
   module Generators # :nodoc:
     class Base < Rails::Generators::NamedBase #:nodoc:
-      protected
+      private
 
         def formats
           [format]
```

when it was protected, it was accessible by subclasses, now not

**Comment by amatsuda** [comment] 2017-03-04 03:17
I'm sorry for the regression. Just pushed a fix in Rails side https://github.com/rails/rails/commit/49d61aed4cc52b8c649f74d23781b3d3f6e01f41
so this will be fixed in the next beta release.

**Closed** 2017-03-04 10:30 UTC

**Comment by edjames** [comment] 2017-03-16 16:36
For anyone who is getting this error who cannot wait for the next beta release, here is a monkey-patch solution until the beta2 drops:

```
# config/initializers/patch/slim.rb

module Slim
  module Generators
    class ScaffoldGenerator
      protected :format
    end
  end
end
```

**Comment by edjames** [comment] 2017-03-16 16:50
For anyone who is getting this error who cannot wait for the next beta release, here is a monkey-patch solution until the beta2 drops:

```
# config/initializers/patch/slim.rb

require 'rails/generators/erb/scaffold/scaffold_generator'

module Slim
  module Generators
    class ScaffoldGenerator < Erb::Generators::ScaffoldGenerator
      protected :format
    end
  end
end
```

**Comment by januszm** [comment] 2017-03-16 16:53
@edjames why not switching to github as a gem source for Rails until beta2 is released?

`gem 'rails', github: 'rails/rails'` ?

**Comment by edjames** [comment] 2017-03-16 17:00
@januszm That would work too of course 👍
